// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApp.Repositories;

#nullable disable

namespace ToDoApp.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoApp.Models.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("IsDone");

                    b.HasIndex("Priority");

                    b.ToTable("Todos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Configure GitHub Actions workflow for automated build, test, and container deployment.",
                            DueDate = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = false,
                            Priority = 2,
                            Title = "Set up CI/CD pipeline"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Add token-based authorization with refresh token rotation and role-based policies.",
                            DueDate = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = true,
                            Priority = 2,
                            Title = "Implement JWT authentication"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Cover CRUD operations and query specifications using xUnit and Moq.",
                            DueDate = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = false,
                            Priority = 1,
                            Title = "Write unit tests for repository layer"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Inspect SQL execution plans, add missing indexes, and apply AsNoTracking where appropriate.",
                            DueDate = new DateTime(2026, 9, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = false,
                            Priority = 1,
                            Title = "Optimize EF Core queries"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Document all public endpoints with request/response schemas using Swagger/OpenAPI.",
                            DueDate = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = false,
                            Priority = 0,
                            Title = "Update API documentation"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
